### ISSUE TITLE
Meta: allow reviewers to add labels and create JOSS-Review label

### ISSUE THREAD

**Issue by kuadrat** [lys-devel/lys#4]
Dear @lys-devel ,

when opening issue #3 I found that I was unable to add or create labels.
It could be useful for the review process to have a label `JOSS-Review` or similar, such that the reviewers can mark the issues that require attention for the publication in JOSS specifically.

**Comment by lys-devel** [comment]
Thank you for your comment. As far as I know, only contributors can edit labels.
Therefore I will add `JOSS_Review` label to all issues raised by the reviewers by myself.

**Comment by kuadrat** [comment]
I see. So only users with write access can create labels. Maybe, though, you could grant the referees [triage access](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#applying-a-label), such that we could apply the labels ourselves. 

I think this would be beneficial because we could label only those issues that are critical with respect to the JOSS review. For example, I opened issues #8 and #9 as legitimate feature requests for the project. They have no influence on the JOSS review and as such should not bear the `JOSS_Review` label.

Just a suggestion, though. We can certainly proceed without these details as well ;)

**Comment by lys-devel** [comment]
Thank you for the suggestion. 
I really understand your opinion regarding the label editing.

I searched how to add access (including triage) to reviewers and test it with one of my colleague.
I found that inviting you as collaborator of this repository is needed. (If you know alternative way, please let me know.)
Since I concern whether all reviewers want to become collaborator of this repository, I will send a invitation when I am asked.

As an alternative way, I prepared a simple issue template for JOSS review.
The `JOSS_Reivew` label is set as default in this template.

If you want to become collaborator of this repository to edit the label, please let me know, @kuadrat ?
Anyway, I will delete `JOSS_Review` label from #8 and #9 following your comment.
